### ISSUE TITLE
大佬能否实现指定频道，而不是所有频道

### ISSUE THREAD

**Issue by linkala** [uk0/telethon_get_media#1]
因为频道太多，车群太多，哈哈大佬懂得
所以能否请大佬更新一下只下载某个指定频道，然后可以过滤一下信息，比如频道内的某些广告图片or视频……

**Comment by uk0** [comment]
可以的 代码自己修改一下就行 用频道的ID

**Comment by kklod** [comment]
外行，不懂就问，看一遍  没找到哪里弄 chanel ID .......

**Comment by uk0** [comment]
> 

emmmm 可以先用事实的下载一下，然后在message 里面找到chanelid ，或者是通过手机转发信息 复制后面的id也可以。

**Comment by uk0** [comment]
> 

后面可能考虑加，因为现在有 去重的脚本 所以当初就没有管 过滤这些事情，毕竟机器流量随便跑，后面加上过滤关键字和一些  media 过滤，可能需要调用第三方api 效率不知道怎么样

**Comment by icefins** [comment]
大佬 加油！虽然小弟 没看懂使用方法 不知道配置哪些参数

**Comment by Jaxton07** [comment]
配置好了启动后一直连接不上啊， 我直接在windows 启动的， 挂不挂梯子都是连接超时，报错如下
Attempt 1 at connecting failed: TimeoutError: 

已解决， 就是代理问题

**Comment by HK-bruc1** [comment]
拿不到api id ，一直错误。。。

**Comment by huagjichen** [comment]
> 拿不到api id ，一直错误。。。

俺也一样，不是error就是[object object]，节点换了一圈也没用，无语了

**Comment by uk0** [comment]
拿不到APP id就换一下 代理。
