### ISSUE TITLE
请问 proxy 应该如何配置呢？

### ISSUE THREAD

**Issue by heitumo** [uk0/telethon_get_media#2]
python3 main.py 

Attempt 1 at connecting failed: ProxyConnectionError: Error connecting to HTTP proxy 127.0.0.1:1089: [Errno 111] Connection refused
Attempt 2 at connecting failed: ProxyConnectionError: Error connecting to HTTP proxy 127.0.0.1:1089: [Errno 111] Connection refused
Attempt 3 at connecting failed: ProxyConnectionError: Error connecting to HTTP proxy 127.0.0.1:1089: [Errno 111] Connection refused

cat zh_cn.config 
[message_download]
PIC_DIR=/Users/x/Desktop
DATA_DIR=/Users/x/Desktop
API_ID=101851
API_HASH=464f1fxxxxxx3057f3be
TG_AUTH_FILE_NAME=auto_download
PROXY_ADDR=127.0.0.1
PROXY_PORT=1089

**Comment by uk0** [comment]
PROXY_ADDR=127.0.0.1
PROXY_PORT=1089 

替换成sock5s 的通道即可

**Comment by Kinnto** [comment]
how can I know the sock5s channel or port? 

xiexie
